#!/bin/bash

brew update

brew install autoconf
brew install automake
brew install bdw-gc
brew install blueutil
brew install brew-cask
brew install cabal-install
brew install cloc
brew install cmake
brew install dfu-util
brew install elixir
brew install erlang
brew install freetype
brew install fzf
brew install gcc
brew install gcc-arm-none-eabi-49
brew install gdbm
brew install ghc
brew install git
brew install giter8
brew install gmp
brew install graphviz
brew install htop
brew install hub
brew install icu4c
brew install idris
brew install isl
brew install jpeg
brew install kubernetes-cli
brew install libevent
brew install libffi
brew install libmpc
brew install libpng
brew install libssh
brew install libtiff
brew install libusb
brew install libyaml
brew install llvm
brew install lua
brew install matplotlib
brew install maven
brew install mpfr
brew install msgpack
brew install node
brew install numpy
brew install openblas
brew install openssl
brew install pcre
brew install peco
brew install pkg-config
brew install postgresql
brew install protobuf
brew install python
brew install python3
brew install readline
brew install reattach-to-user-namespace
brew install ripgrep
brew install ruby
brew install sbt
brew install scala
brew install scipy
brew install scons
brew install selenium-server-standalone
brew install sphinx-doc
brew install sqlite
brew install swig
brew install the_silver_searcher
brew install tmate
brew install tmux
brew install tree
brew install unixodbc
brew install wget
brew install wxmac
brew install xz
brew install yarn
brew install zeromq
brew install zsh
